#!/bin/sh

### Monitors ###
if [ "$(systemd-detect-virt)" = "kvm" ]; then
    export PRIMARY="Virtual-1"
    export SECONDARY=""
elif [ "$(hostname)" = "$HOSTNAME_DESKTOP" ]; then
    export PRIMARY="HDMI-0"
    export SECONDARY="DVI-D-0"

    export KITTY_CONF_FONT_SIZE="font_size 12.0"

    ### Nvidia ###
    export NVIDIA=1
    export __GL_SYNC_TO_VBLANK=1
    export __GL_SYNC_DISPLAY_DEVICE=$PRIMARY
    export VDPAU_NVIDIA_SYNC_DISPLAY_DEVICE=$PRIMARY
elif [ "$(hostname)" = "$HOSTNAME_LAPTOP" ]; then
    export PRIMARY="eDP1"
    export SECONDARY=""

    export KITTY_CONF_FONT_SIZE="font_size 10.0"

    ### Laptop Scaling ###
    # export QT_AUTO_SCREEN_SCALE_FACTOR=1
    # WARNING: Don't do this. Baaaaad
    # export GDK_SCALE=2
    # export GDK_DPI_SCALE=0.5
fi

theming -f
setupMonitors.sh
# xset dpms 300 300 600
# xset s 300
if [ "$(hostname)" = "$HOSTNAME_LAPTOP" ]; then
    (sleep 5 &&
        xset r rate 200 40 &&
        xset +dpms &&
        xset dpms 300 300 600 &&
        xset s off) &
else
    (sleep 5 &&
        xset r rate 200 40 &&
        xset -dpms &&
        xset s off) &
fi

if test "$NVIDIA"; then
    nvidia-settings --config="$XDG_CONFIG_HOME"/nvidia/settings --load-config-only &
fi

# xss-lock -- betterlockscreen -l &
compositor.sh &
unclutter --timeout 5 &
lxpolkit &
numlockx on &
clipctl run &
# xcape -e 'Super_L=Menu;Super_R=Menu' &
easyeffects --gapplication-service &
nm-applet &
blueman-applet &
log_notify.sh "$XDG_CACHE_HOME/log_notify.log" &
xsettingsd &
nextcloud --background &

if [ "$(hostname)" = "$HOSTNAME_LAPTOP" ]; then
    #xsettingsd --config ~/.config/xsettingsd/xsettingsd-laptop.conf &
    libinput-gestures &
else
    imwheel -b "45" &
fi

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

exec awesome
