#!/bin/zsh
if [ "$(hostname)" = "$HOSTNAME_DESKTOP" ]; then
    xrdb -merge "$HOME/.config/Xresources"
elif [ "$(hostname)" = "$HOSTNAME_LAPTOP" ]; then
    xrdb -merge "$HOME/.config/laptop.Xresources"
else
    xrdb -merge "$HOME/.config/Xresources"
fi

setWallpaper.sh
setupMonitors.sh
xset r rate 200 40
# xset dpms 300 300 600
# xset s 300
if [ "$(hostname)" = "$HOSTNAME_LAPTOP" ]; then
    xset +dpms
    xset dpms 300 300 600
else
    xset -dpms
fi
xset s off

if test $NVIDIA; then
    nvidia-settings --config="$XDG_CONFIG_HOME"/nvidia/settings --load-config-only &
fi

# xss-lock -- betterlockscreen -l &
picom.sh &
unclutter --timeout 5 &
lxpolkit &
numlockx on &
clipmanager >/dev/null 2>&1 &
xcape -e 'Super_L=Menu;Super_R=Menu' &
easyeffects --gapplication-service &
nm-applet &
blueman-applet &
playerctld daemon &

if [ "$(hostname)" = "$HOSTNAME_LAPTOP" ]; then
    xsettingsd --config ~/.config/xsettingsd/xsettingsd-laptop.conf &
    libinput-gestures &
else
    imwheel -b "45" &
    xsettingsd &
fi

exec awesome
