#!/bin/zsh
if [ "$(hostname)" = "$HOSTNAME_DESKTOP" ]; then
    xrdb -merge "$HOME/.config/Xresources"
elif [ "$(hostname)" = "$HOSTNAME_LAPTOP" ]; then
    xrdb -merge "$HOME/.config/laptop.Xresources"
else
    xrdb -merge "$HOME/.config/Xresources"
fi

setWallpaper.sh
setupMonitors.sh
xset r rate 200 40
#xset dpms 300 300 600
#xset s 300
xset -dpms
xset s off

if test $NVIDIA; then
    nvidia-settings --config="$XDG_CONFIG_HOME"/nvidia/settings --load-config-only &
fi

xss-lock -- betterlockscreen -l &
imwheel -b "45" &
picom.sh &
unclutter --timeout 5 &
lxpolkit &
numlockx on &
clipmanager >/dev/null 2>&1 &
xcape -e 'Super_L=Menu;Super_R=Menu' &
easyeffects --gapplication-service &
xsettingsd &
nm-applet &
blueman-applet &
playerctld daemon &

exec awesome
