#!/bin/sh
Environment=xorg

# load profile
for file in "/etc/profile" "$HOME/.profile" "/etc/xprofile" "$HOME/.xprofile" "$HOME/.bash_profile"; do
    if [ -f "$file" ]; then
        echo "Loading profile form $file"
        . "$file"
    fi
done

# load resources
for file in "/etc/X11/Xresources" "$HOME/.config/Xresources" "$HOME/.Xresources"; do
    if [ -f "$file" ]; then
        echo "Loading resource form $file"
        xrdb -merge "$file"
    fi
done

# run all system xinitrc shell scripts
if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for i in /etc/X11/xinit/xinitrc.d/* ; do
        if [ -x "$i" ] && [ ! -d "$i" ]; then
            echo "Loading xinit script $i"
            . "$i"
        fi
    done
fi

# load Xsession scripts
if [ -d /etc/X11/Xsession.d ]; then
    for i in /etc/X11/Xsession.d/*; do
        if [ -r "$i" ] && [ -f "$i" ]; then
            echo "Loading xsession script $i"
            . "$i"
        fi
    done
fi

exec dbus-launch bspwm
