#! /bin/sh
bspc rule -r "*"

### monitors ###
setupMonitors.sh &
wait $!
bspc monitor --focus "$PRIMARY"
# TODO: calculate automatically
xdotool mousemove 2880 540

xrdb -merge "$HOME/.config/Xresources"

bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9
bspc monitor DVI-D-0 -d 10 11 12 13

### autostart/restart ###
# stop
for process in "xss-lock" "imwheel" "picom" "sxhkd" "unclutter" "lxpolkit" "extraWM.sh" "xcape" "easyeffects"; do
    if [ "$(pgrep -u "$(id -u)" -nf "$process")" ]; then
        killall -q "$process"
    fi
done
clipctl kill
# wait for processes to terminate
sleep 1

# start
xset r rate 200 40 &
#xset dpms 300 300 600 &
#xset s 300 &
xset -dpms &
xset s off &
setWallpaper.sh &
start_polybar.sh &
wait $!
xss-lock -- betterlockscreen -l &
imwheel -b "45" &
dunst.sh &
picom &
unclutter --timeout 5 &
lxpolkit &
sxhkd &
numlockx on &
clipmanager >/dev/null 2>&1 &
extraWM.sh &
xcape -e 'Super_L=Menu;Super_R=Menu' &
easyeffects --gapplication-service &

nvidia-settings --config="$XDG_CONFIG_HOME"/nvidia/settings --load-config-only &

# wait for wal and start st on desktop 8
[ ! "$(pgrep -f "st -c scratchpad")" ] && (sleep 1 && bspc rule -a scratchpad -o desktop=8 && st -c scratchpad &) &

# source the colors.
. "$SCRIPT_DIR/colors.sh"

### global ###
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config merge_overlapping_monitors true

#bspc config directional_focus_tightness low

bspc config border_width 2
bspc config window_gap 0
bspc config top_padding 24
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0

bspc config split_ratio 0.5

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle false

bspc config normal_border_color "$color8"
bspc config active_border_color "$color8"
bspc config focused_border_color "$color1"
bspc config presel_feedback_color "$color1"

bspc wm --reorder-monitors HDMI-0 DVI-D-0
xsetroot -cursor_name left_ptr &

### rules ###
bspc rule -a Zathura state=tiled
bspc rule -a Steam desktop=9
bspc rule -a discord desktop=10
bspc rule -a pentablet state=floating
