#!/bin/sh
#
# LightDM wrapper to run around X sessions.

echo "Running X session wrapper"

# Load profile
profile="$HOME/.bash_profile"
if [ -f "$profile" ]; then
    echo "Loading profile from $profile"
    . "$profile"
fi

# Load resources
resources="$HOME/.config/Xresources"
if [ -f "$resources" ]; then
    echo "Loading resource: $resources"
    xrdb "$resources"
fi

# Load xmodmap
modmap="$HOME/.config/Xmodmap"
if [ -f "$modmap" ]; then
    echo "Loading modmap: $modmap"
    xmodmap "$modmap"
fi

# Run all system xinitrc shell scripts
xinitdir="/etc/X11/xinit/xinitrc.d"
if [ -d "$xinitdir" ]; then
    for script in $xinitdir/*; do
        echo "Loading xinit script $script"
        if [ -x "$script" -a ! -d "$script" ]; then
            . "$script"
        fi
    done
fi

echo "X session wrapper complete, running session $@"

exec $@
