theme:
    active: Red
    banner: Green
    error_border: Red
    error_text: Blue
    hint: Green
    hovered: Red
    inactive: Gray
    playbar_background: Black
    playbar_progress: Green
    playbar_progress_text: White
    playbar_text: White
    selected: Red
    text: White
    #header: White
    #analysis_bar: Red
    #analysis_bar_text: White

keybindings:
    increase_volume: "="

behavior:
    seek_milliseconds: 5000
    volume_increment: 5
    tick_rate_milliseconds: 5
    set_window_title: true
