-- ==================== NVIM init ==================== --
-- TODO: Telescope, alpha color, fix weird snippet bug

require("plugins")
require("impatient")
require("mappings")
require("settings")
require("lsp")
require("completion")
require("treesitter")
require("tele")
require("pairs")
require("comment")
require("start")
require("tree")
require("git")
require("buffer")
require("statusline")
require("spell")
require("debugui")
